export const Database = () => {
 return[
    {
      nombre: 'coche azul',
      marca: "Mothercare",
      TipoPrenda: 'coche',
      Precio:"500000",
      imagenUrl:"/src/assets/img/prendas_mothercare/coche_azul.jpg"
    },
{
  nombre: 'coche doble',
  marca: 'Mothercare',
  TipoPrenda: 'coche',
  Precio: '546000',
  imagenUrl: '/src/assets/img/prendas_mothercare/coche_doble.jpg',
  
},
{
  nombre: 'coche doble gris',
  marca: 'Mothercare',
  TipoPrenda: 'coche',
  Precio: '5046000',
  imagenUrl: '/src/assets/img/prendas_mothercare/coche_doble_gris.jpg',
},
{
  nombre: 'coche gris',
  marca: 'Mothercare',
  TipoPrenda: 'coche',
  Precio: '504600',
  imagenUrl: '/src/assets/img/prendas_mothercare/coche_gris.jpg',
},
{
  nombre: 'coche gris oscuro',
  marca: 'Mothercare',
  TipoPrenda: 'coche',
  Precio: '554000',
  imagenUrl: '/src/assets/img/prendas_mothercare/coche_gris_oscuro.jpg',
},
{
  nombre: 'coche naranja',
  marca: 'Mothercare',
  TipoPrenda: 'coche',
  Precio: '550050',
  imagenUrl: '/src/assets/img/prendas_mothercare/coche_naranja.jpg',
},
{
  nombre: 'coche negro',
  marca: 'Mothercare',
  TipoPrenda: 'coche',
  Precio: '556000',
  imagenUrl: '/src/assets/img/prendas_mothercare/coche_negro.jpg',
},
{
  nombre: 'coche rojo',
  marca: 'Mothercare',
  TipoPrenda: 'coche',
  Precio: '590000',
  imagenUrl: '/src/assets/img/prendas_mothercare/coche_rojo.jpg',
},
{
  nombre: 'coche rosa',
  marca: 'Mothercare',
  TipoPrenda: 'coche',
  Precio: '501010',
  imagenUrl: '/src/assets/img/prendas_mothercare/coche_rosa.jpg',
},
{
  nombre: 'cuna blanca ',
  marca: 'Mothercare',
  TipoPrenda: 'cuna',
  Precio: '510010',
  imagenUrl: '/src/assets/img/prendas_mothercare/cuna_blanca.jpg',
},
{
  nombre: 'cuna blanca con mate',
  marca: 'Mothercare',
  TipoPrenda: 'cuna',
  Precio: '520200',
  imagenUrl: '/src/assets/img/prendas_mothercare/cuna_blanca_con_mate.jpg',
},
{
  nombre: 'cuna grande gris claro',
  marca: 'Mothercare',
  TipoPrenda: 'cuna',
  Precio: '520300',
  imagenUrl: '/src/assets/img/prendas_mothercare/cuna_grande_gris_claro.jpg',
},
{
  nombre: 'cuna grande gris mate',
  marca: 'Mothercare',
  TipoPrenda: 'cuna',
  Precio: '510111',
  imagenUrl: '/src/assets/img/prendas_mothercare/cuna_grande_gris_mate.jpg',
},
{
  nombre: 'cuna gris clara',
  marca: 'Mothercare',
  TipoPrenda: 'cuna',
  Precio: '1200110',
  imagenUrl: '/src/assets/img/prendas_mothercare/cuna_gris_clara.jpg',
},
{
  nombre: 'cuna mate',
  marca: 'Mothercare',
  TipoPrenda: 'cuna',
  Precio: '220000',
  imagenUrl: '/src/assets/img/prendas_mothercare/cuna_mate.jpg',
},
{
  nombre: 'cuna mediana gris ',
  marca: 'Mothercare',
  TipoPrenda: 'cuna',
  Precio: '199999',
  imagenUrl: '/src/assets/img/prendas_mothercare/cuna_mediana_gris.jpg',
},{
  nombre: 'cuna negra',
  marca: 'Mothercare',
  TipoPrenda: 'cuna',
  Precio: '1500100',
  imagenUrl: '/src/assets/img/prendas_mothercare/cuna_negra.jpg',
},
{
  nombre: 'silla para bebe azul',
  marca: 'Mothercare',
  TipoPrenda: 'silla',
  Precio: '111000',
  imagenUrl: '/src/assets/img/prendas_mothercare/silla_para_bebe_azul.jpg',
},
{
  nombre: 'silla para bebe roja ',
  marca: 'Mothercare',
  TipoPrenda: 'silla',
  Precio: '110000',
  imagenUrl: '/src/assets/img/prendas_mothercare/silla_para_bebe_roja.jpg',
},
{
  nombre: 'silla para bebe gris',
  marca: 'Mothercare',
  TipoPrenda: 'silla',
  Precio: '250000',
  imagenUrl: '/src/assets/img/prendas_mothercare/silla_para_bebe_gris.jpg',
},
]
}
