export default DataBase = () => {
 
    return [{


      nombre: 'Abrigo Azul Claro',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"NafNaf",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/abrigo_azul_claro_mujer_nafna.png",
    },
    {
      nombre: 'Abrido Gris Mate',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"250000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/abrigo_gris_mate_mujer_nafnaf.png",
    },
    {
      nombre: 'Abrigo Gris',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"250000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/abrigo_gris_mujer_nafnaf.png",
    },
    {
      nombre: 'Abrigo Verde',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"250000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/abrigo_verde_mujer_nafnaf.png",
    },
    {
      nombre: 'Camisa Azul',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"250000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/camisa_azul_mujer_nafnaf.png",
    },
    {
      nombre: 'Camisa Blanca',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"310000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/camisas_blanca_mujer_nafnaf.png",
    },
    {
      nombre: 'Camisa Negra ',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"315000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/camiseta_negra_mujer_nafnaf.png",
    },
    {
      nombre: 'Camisa Cafe',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"320000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/camiseta_negra_mujer_nafnaf.png",
    },
    {
      nombre: 'Enterizo Cafe',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"210000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/enterizo_cafe_mujer_nafnaf.png",
    },
    {
      nombre: 'Enterizo Gris',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"220000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/enterizo_gris_mujer_nafnaf.png",
    },
    {
      nombre: 'Enterizo Negro',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"320000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/enterizo_negro_mujer_nafnaf.png",
    },
    {
      nombre: 'Enterizo Rojo',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"215000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/enterizo_rojo_mujer_nafnaf.png",
    },
    {
      nombre: 'Pantalon Acampanado Azul',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"2700000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/pantalon_acampanado_azul_mujer_nafnaf.png",
    },
    {
      nombre: 'Pantalon Acampanado Vinotinto',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"2700000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/pantalon_acampanado_vinotinto_mujer_nafnaf.png",
    },
    {
      nombre: 'Pantalon Cargo',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"2700000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/pantalon_cargo_mujer_nafnaf.png",
    },
    {
      nombre: 'Pantalon Negro',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"2700000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/pantalon_negro_mujer_nafnaf.png",
    },
    {
      nombre: 'Short Verde',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"200000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/short_verde_mujer_nafnaf.png",
    },
    {
      nombre: 'Zapatos Beige',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"200000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/zapato_beige_nafnaf.png",
    },
    {
      nombre: 'Zapatos Blanco',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"200000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/zapatos_blanco_nafnaf.png",
    },
    {
      nombre: 'Zapatos Cafe',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"200000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/zapatos_cafes_nafnaf.png",
    },
    {
      nombre: 'Zapatos Leopardo',
      marca: NafNaf,
      TipoPrenda: 'Abrigo',
      Precio:"200000",
      Sexo:"Femenino",
      imagenUrl:"src/assets/img/prendas_nafnaf/zapatos_leopardo_nafnaf.png",
    }
  ]
   
}
